version: '3.8'

services:
  app:
    image: your-image-name:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      NODE_ENV: production
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  load-balancer:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
